### ISSUE TITLE
add adjective to crime

### ISSUE THREAD

**Issue by 6mc** [mcanwoo/VICE-Title-Generator#2]
hey guys ı want you to add a noun to crimes
EXAMPLE:
Bride Kidnapping in Yemen
Soccer Hooliganism in Turkey

Bride and Soccer are the nouns of these crimes

**Comment by enjeck** [comment]
Don't you mean add nouns? Like maybe "bride", "soccer"?

**Comment by 6mc** [comment]
yes nouns like 'bride' and 'soccer'
